# Generated by Django 4.2.7 on 2023-11-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
