# Generated by Django 4.2.7 on 2023-11-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
