# Generated by Django 4.2.7 on 2023-12-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
