# Generated by Django 4.2.7 on 2023-11-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0002_applied_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_coupon',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
