# Generated by Django 4.2.7 on 2023-11-28 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0004_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Debit', max_length=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('d3c5e357-e8cb-49d4-8a36-8310c39bfc74'), editable=False, unique=True),
        ),
    ]
