# Generated by Django 4.2.7 on 2023-11-30 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0005_rename_balance_wallet_amount_wallet_balance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance_type',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], default='Credit', max_length=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
