# Generated by Django 4.2.7 on 2023-12-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acuser', '0006_alter_wallet_balance_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applied_coupon',
        ),
    ]
