# Generated by Django 4.2.7 on 2023-11-24 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_carttotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartTotal',
        ),
    ]
