# Generated by Django 4.2.7 on 2023-11-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('COD', 'COD'), ('Paid', 'Paid')], default='COD', max_length=20),
        ),
    ]
