# Generated by Django 4.2.7 on 2023-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderitem_status_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
