# Generated by Django 4.2.7 on 2023-11-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('COD', 'COD'), ('PAYPAL', 'PAYPAL')], default='COD', max_length=20),
        ),
    ]
