# Generated by Django 4.2.7 on 2023-11-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('return_status', models.CharField(choices=[('Return Pending', 'Return Pending'), ('Returned', 'Returned')], default='Return Pending', max_length=20)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_products', to='order.orderitem')),
            ],
        ),
    ]
