# Generated by Django 4.2.7 on 2023-11-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_returnedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='Ordered', max_length=20),
        ),
    ]
