# Generated by Django 4.2.7 on 2023-11-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnedproduct',
            name='order_item',
        ),
    ]
