# Generated by Django 4.2.7 on 2023-11-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_returnedproduct_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='returned_products', to='order.order'),
            preserve_default=False,
        ),
    ]
